# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViperDemo
  
  pod 'ObjectMapper'
  pod 'Alamofire' 
  pod 'Swinject'

  target 'ViperDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire' 
    pod 'ObjectMapper'
    pod 'Swinject'
  end

end
